### ISSUE TITLE
训练trainer_ner报错

### ISSUE THREAD

**Issue by leizhu1989** [Xie-Minghui/EntityRelationExtraction#12]
你好，我训练的时候报了个错啊：
USE_CUDA....
Run EntityRelationExtraction NER ...
Traceback (most recent call last):
  File "mains/trainer_ner.py", line 164, in <module>
    data_processor = ModelDataPreparation(config)
  File "/home/ctgcdt/zhulei/NLP/EntityRelationExtraction/data_loader/process_ner.py", line 27, in __init__
    self.get_type2id()
  File "/home/ctgcdt/zhulei/NLP/EntityRelationExtraction/data_loader/process_ner.py", line 103, in get_type2id
    self.token2id[line[0]] = cnt
IndexError: list index out of range

字典解析错误吗，我用的是官方的vocab.txt

**Comment by leizhu1989** [comment]
我修改了下解析vocab代码这个解决了
