### ISSUE TITLE
文件缺了vec.txt

### ISSUE THREAD

**Issue by Cloudye02** [Xie-Minghui/EntityRelationExtraction#16]
../data/vec.txt这个文件好像没有

**Comment by Cloudye02** [comment]
这个词向量文件要自己生成吗？

**Comment by Xie-Minghui** [comment]
> 这个词向量文件要自己生成吗？

这个我忘记了，不是词向量文件吧，就是一个词表吗？

**Comment by iaobai** [comment]
这个 config_ner.py中的
self.vocab_file = '../data/vocab.txt'
能用Bert模型文件中的vocab.txt替代吗

**Comment by Xie-Minghui** [comment]
> 这个 config_ner.py中的 self.vocab_file = '../data/vocab.txt' 能用Bert模型文件中的vocab.txt替代吗

你可以试试，我也忘记了，应该是的

**Comment by Fuuto-Joker** [comment]
> > 这个 config_ner.py中的 self.vocab_file = '../data/vocab.txt' 能用Bert模型文件中的vocab.txt替代吗
> 
> 你可以试试，我也忘记了，应该是的

Traceback (most recent call last):
  File "C:\Users\m1879\Desktop\EntityRelationExtraction\data_loader\process_rel.py", line 206, in <module>
    process = DataPreparationRel(config)
  File "C:\Users\m1879\Desktop\EntityRelationExtraction\data_loader\process_rel.py", line 13, in __init__
    self.get_token2id()
  File "C:\Users\m1879\Desktop\EntityRelationExtraction\data_loader\process_rel.py", line 82, in get_token2id
    self.word2id[line.split()[0]] = cnt
IndexError: list index out of range

试了，但报错了

**Comment by MarisaMagic** [comment]
> > > 这个 config_ner.py中的 self.vocab_file = '../data/vocab.txt' 能用Bert模型文件中的vocab.txt替代吗
> > 
> > 
> > 你可以试试，我也忘记了，应该是的
> 
> Traceback (most recent call last): File "C:\Users\m1879\Desktop\EntityRelationExtraction\data_loader\process_rel.py", line 206, in process = DataPreparationRel(config) File "C:\Users\m1879\Desktop\EntityRelationExtraction\data_loader\process_rel.py", line 13, in **init** self.get_token2id() File "C:\Users\m1879\Desktop\EntityRelationExtraction\data_loader\process_rel.py", line 82, in get_token2id self.word2id[line.split()[0]] = cnt IndexError: list index out of range
> 
> 试了，但报错了

vocab.txt 文件中可能有空行，line.strip().split(' ') 返回的列表 line 可能是空的，line[0] 访问列表第一个元素就会导致越界。把 vocab.txt 中的空行删掉，或者在 line[0] 访问列表第一个元素 之前添加当 line 列表为空时跳过的语句即可。
